# Generated by Django 2.2.1 on 2019-06-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_name',
            field=models.CharField(default='Anonymous User', max_length=45),
        ),
    ]
